require "kudep.options"
require "kudep.keymaps"
require "kudep.plugins"
require "kudep.colorscheme"
require "kudep.toggleterm"
require "kudep.nvim-tree"
require "kudep.cmp"
require "kudep.lsp"
require "kudep.gitsigns"
-- require "kudep.telescope"
require "kudep.treesitter"
-- require "kudep.autopairs"
-- require "kudep.comment"
-- require "kudep.bufferline"
-- require "kudep.lualine"
-- require "kudep.project"
-- require "kudep.impatient"
-- require "kudep.indentline"
-- require "kudep.alpha"
-- require "kudep.whichkey"
-- require "kudep.autocommands"
